### ISSUE TITLE
armhf (raspberry pi) support

### ISSUE THREAD

**Issue by garret** [jlesage/docker-czkawka#1]
I just discovered this fantastic project and your docker image. Since I have my files attached to a volume on a Raspberry Pi 4B, I was wondering if I could deploy such docker image also there. From the tag I can see that only amd64 is supported though. 

I know I could mount the drives with sshfs on another amd64 system. However, to keep disk reading/writing more performing I would prefer to have everything on the Pi itself. Additionally, I have terabytes of data that I should process and have heard that sshfs is not so performing. 

Would it be easy to add support also for armhf?

**Comment by jlesage** [comment]
I'm working on this.  Everything is in place to have a multi-arch image.

**Comment by jlesage** [comment]
ARM is now supported with the latest image.
