### ISSUE TITLE
Unable to find results saved to file

### ISSUE THREAD

**Issue by dmei4380** [jlesage/docker-czkawka#13]
When saving results to a file, czkawka says it stored results in results_similar_images.txt, however that file is not found anywhere within the container. I checked the config and storage folders, as well as doing an ls -lR on /. Any ideas if this is a bug with czkawka or the configuration? Your dupesguru implementation seems to be better as it asks for the save location, however czkawka has built in image preview which is nice.

**Comment by jlesage** [comment]
Thanks for reporting.  Czkawka doesn't specify a full path when saving the file... I will implement a fix for this.

**Comment by jlesage** [comment]
Fixed with the latest image.
