### ISSUE TITLE
Similar videos error

### ISSUE THREAD

**Issue by wwray** [jlesage/docker-czkawka#14]
```
############### ERRORS(2) ###############
Cannot find proper installation of FFmpeg
Similar Videos don't work currently with snap, if you want help look at - \u2068https://github.com/snapcrafters/ffmpeg/issues/73\u2069
```

I am getting the above error when trying to search for similar videos. There is a closed issue that provides a fix that works, but everytime the container updates it comes back.

**Comment by jlesage** [comment]
Fixed with the latest image.
