### ISSUE TITLE
Add CJK font support

### ISSUE THREAD

**Issue by sjtuross** [jlesage/docker-czkawka#15]
It looks like Chinese/Japanese/Korean characters are not shown properly, even if I switch to the respective UI language. Below Settings screenshot is just an example. It affects all file names. Any chance to resolve?

![image](https://user-images.githubusercontent.com/940110/214528638-eb65f683-2f6e-4fa6-bd89-ac8b25caca0d.png)
![image](https://user-images.githubusercontent.com/940110/214529701-6e8bd93b-43c9-44c5-a2ae-68435b0243d8.png)

**Comment by jlesage** [comment]
Did you set the `ENABLE_CJK_FONT` environment variable?  See https://github.com/jlesage/docker-czkawka#environment-variables

**Comment by sjtuross** [comment]
Thank you for your guidance. I installed it by Unraid template which doesn't include this environment variable. Now I manually set it and CJK font shows properly.
