### ISSUE TITLE
Gtk-WARNING: in log

### ISSUE THREAD

**Issue by nodecentral** [jlesage/docker-czkawka#18]
Hi

I’ve just installed a docker instance of czkawka, which looks great - many thanks for sharing it..

While the install seemed to go well, in the console / log i noticed the following error, and wanted to find out what it is, and if there is something I should look to do?

````
[supervisor  ] starting service 'app'...
[app         ] (czkawka_gui:613): Gtk-WARNING **: 08:50:56.588: Unable to acquire the address of the accessibility bus: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files. If you are attempting to run GTK without a11y support, GTK_A11Y should be set to 'none'.
[supervisor  ] all services started.
````

**Comment by jlesage** [comment]
This warning message is not harmful and should not cause any issue with Czkawka.

Still, as indicated by the message, I will add the `GTK_A11Y=none` variable to get ride of the message.  So you should no longer see it with the next version of the container image :)

**Comment by nodecentral** [comment]
Awesome, many thanks @jlesage

**Comment by jlesage** [comment]
This issue can now be closed.
