### ISSUE TITLE
Czkawka 3.2.0?

### ISSUE THREAD

**Issue by nearcatch** [jlesage/docker-czkawka#2]
Been out for about a month now, but this image still uses 3.1.0.

**Comment by nearcatch** [comment]
Bumping in hopes of 3.3.1 - https://github.com/qarmin/czkawka/releases/

**Comment by jlesage** [comment]
Still crashing with 3.3.1 :(

I'm trying to build differently to see if it can help...

**Comment by jlesage** [comment]
We were not able to upgrade yet because the UI was crashing.  See https://github.com/qarmin/czkawka/issues/416.

Now that we better understand how to avoid this crash, I will be able to provide a new Docker image with the latest version of Czkawka.

**Comment by jlesage** [comment]
New image now available!
