### ISSUE TITLE
Configurable cache directory

### ISSUE THREAD

**Issue by rubenvarela** [jlesage/docker-czkawka#7]
Would it be possible to add support to specify the cache location via a volume?

**Comment by jlesage** [comment]
What directory exactly you are talking about?

**Comment by rubenvarela** [comment]
I've been giving it a try on macOS. The path here is of course different. 

Current path I'm seeing here is, `$HOME/Library/Caches/pl.Qarmin.Czkawka`

If I go to Settings, I can click on 'Open cache folder'. 

----

Let me spin it up on Linux and see what it's set to there.

**Comment by rubenvarela** [comment]
On Debian at least, the path is set to `$HOME/.cache/czkawka`

**Comment by jlesage** [comment]
This folder is already under `/config` in the container.  `/config` is a directory meant to mapped to the host.
See https://github.com/jlesage/docker-czkawka#data-volumes

**Comment by rubenvarela** [comment]
@jlesage thank you! I'll review
