### ISSUE TITLE
Czkawka 4.0 requires ffmpeg for new "similar videos" functionality

### ISSUE THREAD

**Issue by nearcatch** [jlesage/docker-czkawka#8]
```
############### ERRORS(2) ###############
Cannot find proper installation of FFmpeg
Similar Videos don't work currently with snap, if you want help look at - \u2068https://github.com/snapcrafters/ffmpeg/issues/73\u2069
```
Above error occurs when trying to use the feature in 1.6.0 of the container. If I run `apk add  --no-cache ffmpeg` in the container shell then the feature works fine. Not sure if that's the best version of ffmpeg to use though. I usually use https://github.com/jrottenberg/ffmpeg when encoding videos; maybe it can be pulled in via the Dockerfile?

[Czkawka PR mentioning that ffmpeg is required](https://github.com/qarmin/czkawka/pull/460)

**Comment by jlesage** [comment]
Thanks for reporting, this is now fixed!
