### ISSUE TITLE
CZkawka 5.0.2 update

### ISSUE THREAD

**Issue by arsaboo** [jlesage/docker-czkawka#9]
Can we please update this to the latest release (5.0.2)...thanks!

**Comment by jlesage** [comment]
Just to let you know that I'm working on this.  The baseimage now supports Alpine 3.16, required to build the latest Czkawka.

**Comment by chbndrhnns** [comment]
Would be so cool!

**Comment by jlesage** [comment]
Version integrated in the latest image.
